// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.33.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String generateRandomName({dynamic hint}) =>
    RustLib.instance.api.generateRandomName(hint: hint);

Future<void> startRustSender(
        {required String name,
        required String relay,
        required List<String> files,
        dynamic hint}) =>
    RustLib.instance.api
        .startRustSender(name: name, relay: relay, files: files, hint: hint);

Future<String> startRustReceiver(
        {required String relay, required String transfername, dynamic hint}) =>
    RustLib.instance.api.startRustReceiver(
        relay: relay, transfername: transfername, hint: hint);
