[package]
name = "rust_lib_flutter_test_gui"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.0.0-dev.33"
hex = "0.4.3"
rand = "0.8.5"
caesar-core = { path = "../caesar-core" }
anyhow = "1.0.83"
