[package]
name = "caesar-tui"
version = "0.0.1"
edition = "2021"
authors = ["Manuel Keidel, Patryk Hegenberg, Krzysztof Stankiewicz"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
caesar-core = { path = "../caesar-core" }
